# Question 1

Create a null vector of size 10 but the fifth value which is 1 

In [ ]:
# Import the numpy package under the name np
import numpy as np

# you answer here


# Question 2

Create a 10x10 array with random values and find the  maximum values

In [ ]:
# Import the numpy package under the name np
import numpy as np

# you answer here


# Question 3

How to add a border (filled with 0's) around the following existing array? The end results should be a matrix of 7 x 7 matrix with all 0's along the four boarders. 

`Z = np.ones((5,5))`

In [5]:
# Import the numpy package under the name np
import numpy as np

# you answer here


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
