# Question 1

Create a null vector of size 10 but the fifth value which is 1 

In [13]:
# Importing numpy package 
import numpy as np

# you answer here

# Creating a null vector of size 10 with dtype float
null_vector = np.zeros(10, dtype=float)

# Set the fifth value to 1
null_vector[4] = 1

print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Question 2

Create a 10x10 array with random values and find the  maximum values

In [11]:
# Importing numpy package 
import numpy as np

# you answer here

# Create a 10x10 array with random values
array = np.random.rand(10, 10)

# Find the maximum value in the array
max_value = array.max()

print(array)

print(f"The maximum value is {max_value}")


[[0.53663472 0.46842981 0.89988024 0.35508798 0.91922394 0.11373874
  0.06489737 0.68553324 0.39573773 0.16174197]
 [0.52306807 0.21228133 0.59938712 0.56478064 0.71727846 0.07891033
  0.57473659 0.50490431 0.62135367 0.80250376]
 [0.71032544 0.9028687  0.96346128 0.71497025 0.79760814 0.42687999
  0.89734677 0.35820688 0.95722165 0.92460512]
 [0.64270173 0.46454764 0.15463256 0.71285976 0.521906   0.05127008
  0.09810862 0.86255305 0.51065598 0.58242578]
 [0.04576932 0.23626065 0.82645284 0.85656284 0.19510351 0.37428717
  0.24298678 0.68518375 0.92230609 0.14576182]
 [0.69211447 0.60136208 0.27108721 0.85808507 0.230921   0.72424283
  0.14468147 0.45121197 0.30191056 0.17232006]
 [0.4202797  0.9278376  0.07362336 0.19197526 0.10738587 0.04152326
  0.4829534  0.02753404 0.91329718 0.16372069]
 [0.8221705  0.21296064 0.11827526 0.79382032 0.19965059 0.29536974
  0.92907662 0.68168068 0.73403447 0.07352746]
 [0.43555802 0.6817849  0.06123962 0.88112922 0.46489635 0.63098278
  0.67462714

# Question 3

How to add a border (filled with 0's) around the following existing array? The end results should be a matrix of 7 x 7 matrix with all 0's along the four boarders. 

`Z = np.ones((5,5))`

In [12]:
# Import the numpy package under the name np
import numpy as np

# you answer here

# Create an array of ones
Z = np.ones((5, 5))

# Create a new array of zeros with the desired shape
Z_border = np.zeros((7, 7))

# Copy the original array into the center of the new array
Z_border[1:-1, 1:-1] = Z

print(Z_border)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
